---
# tasks file for role_httpd
#
- name: "installation git"
  package:
   name: "git"
   state: present

- name: "recuperation repo git"
  git:
    repo: "https://github.com/diranetafen/static-website-example.git"
    dest: "/home/ubuntu/dest/static-website-example"

- name: "Deploiement conteneur httpd"
  docker_container:
    name: httpd
    image: "httpd"
    ports:
      - "8080:80"
    volumes:
      - "/home/ubuntu/dest/static-website-example:/usr/local/apache2/htdocs"
